version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    # branches:
    #   only:
    #     - master
    working_directory: ~/stuart # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:9.10.0 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: yarn
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build for deployment
          command: yarn build
      - run:
          name: clone the deployment repo
          working_directory: ~/stuart
          command: git clone --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/rishabh1403/bt.git
      - run:
          name: clear old deployment files
          command: rm -rf bt/*
      - run:
          name: copy new build
          command: cp -vr public/* bt
      - deploy:
          name: Deploy new build
          working_directory: ~/stuart/bt
          command: |
            git add .
            git config credential.helper 'cache --timeout=120'
            git config user.email "mailrishabh1403@gmail.com"
            git config user.name "Rishabh Jain"
            git commit --allow-empty -m "Deployed From Circle CI on `date`"
            git push -q https://${DEPLOY_KEY}@github.com/rishabh1403/bt.git master